# data
feeder: feeder.feeder.Feeder
train_feeder_args:
  multimodal: False
  dataset: "ntu"
  data_prefix : 'data/ntu/RGB_videos/nturgb+d_videos_c'  
  split: 'xsub_train'
  test_mode: False
  ann_file : 'data/ntu/ntu60_hrnet.pkl'
  pipeline: 
    - type: "MMUniformSampleFrames"
      clip_len: 
        RGB: 40
      num_clips: 1
    - type: "MMDecode"
    - type: "MMCompact"
      padding: 0.1
      hw_ratio: 1.
      allow_imgpad: True

    - type: Resize
      scale: !!python/tuple
        - 256
        - 256
      keep_ratio: false

    - type: RandomResizedCrop
      area_range: !!python/tuple
        - 0.56
        - 1.0

    - type: Resize
      scale: !!python/tuple
        - 224
        - 224
      keep_ratio: false
    
    - type: RGBToGrayscale

    - type: Flip
      flip_ratio: 0.5

    - type: FormatShape
      input_format: NCTHW

    - type: Collect
      keys:
        - imgs
        - label
        - frame_dir
      meta_keys: []

    - type: ToTensor
      keys:
        - imgs
        - label
        - frame_dir


# data
val_feeder_args:
  multimodal: False
  dataset: "ntu"
  data_prefix : 'data/ntu/RGB_videos/nturgb+d_videos_c'  
  split: 'xsub_val'
  test_mode: True
  ann_file : 'data/ntu/ntu60_hrnet.pkl'
  pipeline: 
    - type: "MMUniformSampleFrames"
      clip_len: 
        RGB: 40
      num_clips: 1
    - type: "MMDecode"
    - type: "MMCompact"
      padding: 0.1
      hw_ratio: 1.
      allow_imgpad: True

    - type: Resize
      scale: !!python/tuple
        - 224
        - 224
      keep_ratio: false
    
    - type: RGBToGrayscale

    - type: FormatShape
      input_format: NCTHW

    - type: Collect
      keys:
        - imgs
        - label
        - frame_dir

      meta_keys: []

    - type: ToTensor
      keys:
        - imgs
        - label


# model
model: model.transformer_rgb.Transformer
model_args:
  dim_in: 2
  num_classes: 60
  dim_feat: 256
  depth: 8
  num_heads: 8
  mlp_ratio: 4
  num_frames: 40
  num_joints: 17
  patch_size: 17
  t_patch_size: 1
  qkv_bias: True
  qk_scale: None
  drop_rate: 0.
  attn_drop_rate: 0.
  drop_path_rate: 0.3
  block_norm_first: True
  protocol: finetune

# training
epochs: 100
warmup_epochs: 5
batch_size: 1
lr: 5e-4
layer_decay: 0.8
smoothing: 0.1